---
title: "simulation"
output: pdf_document
date: "2023-03-13"
---
```{r}
rm(list = ls())
```

```{r}
library(tidyverse)
library(MASS)
```

```{r}
set.seed(0)
#1 set of parameters 
m0 <- 1
m1 <- 2
sd0 <- 1
sd1 <- 2
sd01 <- 1.5
C <- 3
#2 Simulate the (ϵ0, ϵ1) for N equals to 10 million individuals
N <- 10 ^ 7
sig <-rbind (c( sd0 ^2 , sd01 ) ,c( sd01 , sd1 ^2) )
mu <- c(0, 0)
data <- as.data.frame(mvrnorm(n = N, mu = mu, Sigma = sig))
colnames(data) <- c("e0", "e1")
#3, 4 Create the columns for w0 and w1,and enerate the column I that take binary value.

data <- data %>%
  mutate(w0 = m0 + e0,
         w1 = m1 + e1,
         I = ifelse(w1 - w0 - C > 0, 1, 0))
#5 Calculate E[w0∣I], E[w1∣I], Q0, Q1
data_I <- data %>% filter(., I ==1)
sapply(data_I, FUN = mean)
#6 Calculate RHS of equation 
sd_v <- sqrt(sd0 ^ 2 + sd1 ^ 2 - 2 * sd01)
rho <- sd01 / (sd0 * sd1)
z <- (m0 - m1 + C)/ sd_v
E_w0_I <- m0 + sd0 * sd1 / sd_v * (rho - sd0 / sd1) * (dnorm(z) / (1 - pnorm(z)))
E_w1_I <- m0 + sd0 * sd1 / sd_v * (sd1 / sd0 - rho) * (dnorm(z) / (1 - pnorm(z)))
Q_0 <- E_w0_I - m0
Q_1 <- E_w1_I - m1
E_w0_I
E_w1_I
Q_0
Q_1
```